[build]  
  command = "cd client && yarn && yarn build && cd ../types && yarn && cd ../server && tsc --project tsconfig.server.json"
  publish = "client/dist"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200